### PR TITLE
Fix Web docs link

### PR DESCRIPTION
**Pull request by cx0der**
Motivation:

Correct the link to web docs.

### CODE REVIEW

**Comment by pk-work** [comment]
Hi @cx0der, thanks for your commit. The docs you have linked are the docs from `vertx-web-openapi`. But this repo is for `vertx-openapi`, a new OpenAPI library that will most likely be released with Vert.x 4.4.0.

So the link is not wrong.

**Comment by cx0der** [comment]
In that case what should be the correct link? At the moment the link is broken.

**Comment by pk-work** [comment]
As I said it is not yet released, therefore the website does not have a doc. Wait for the 4.4.0 release on March 1st (most likely).

For now you can find example code here: https://github.com/eclipse-vertx/vertx-openapi/tree/main/src/main/java/examples
And the doc here: https://github.com/eclipse-vertx/vertx-openapi/tree/main/src/main/asciidoc

**Comment by cx0der** [comment]
Understood. Thanks for the quick review turnaround. Closing the PR.

**Pull request closed without merging**
